# Generated by Django 5.2.3 on 2025-06-25 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0003_timesheet_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
