# Generated by Django 5.2.3 on 2025-06-25 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0004_alter_timesheet_end_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='day',
            old_name='date',
            new_name='day_date',
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='day',
            unique_together={('timesheet', 'day_date')},
        ),
    ]
