# Generated by Django 5.2.3 on 2025-06-25 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0005_rename_date_day_day_date_alter_timesheet_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('development', 'Development'), ('code_review', 'Code Review'), ('bug_fixing', 'Bug Fixing'), ('testing', 'Testing'), ('internal_meeting', 'Internal Meeting'), ('external_meeting', 'External Meeting'), ('admin', 'Admin'), ('documentation', 'Documentation'), ('support', 'Support'), ('other', 'Other')], default='other', max_length=20)),
                ('hours_logged', models.FloatField()),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_entries', to='timesheets.day')),
            ],
        ),
    ]
