# Generated by Django 5.2.3 on 2025-07-01 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0007_alter_task_options_day_total_hours_logged_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('name', 'start_date')},
        ),
    ]
